<?php
/* @var $this Mage_Core_Block_Template */

/** @var Mage_Sales_Model_Order $order */
$orderId = $this->getOrderId();
$order = Mage::getModel('sales/order')->load($orderId);
$payment = $order->getPayment();
$paggiOrderId = $payment->getAdditionalInformation('order_id');

/** @var Paggi_Payment_Helper_Data $helper */
$helper = Mage::helper('paggi');

$response = $helper->getApi()->getOrder($order, $paggiOrderId);
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head'); ?>
    <style type="text/css">
        html,body { height:100%; }
        a{
            font-size: 11px;
        }
        dl {
            padding: 0.5em;
            transition: 0.5s;
            -webkit-transition: 0.5s;
        }
        dt {
            float: left;
            clear: left;
            width: 250px;
            text-align: right;
            font-weight: bold;
            color: #e02f00;
            border: 1px solid #dedede;
            background: #efefef;
            margin: 0 0 0.5em 0;
        }
        dt::after {
            content: ":";
        }
        dd {
            margin: 0 0 0.5em 260px;
            background: #fefefe;
            border: 1px solid #dedede;
        }
    </style>
</head>
<body id="html-body" style="background:#fff;">
<div id="preview" class="cms-revision-preview">
    <?php if (property_exists($response, 'status')): ?>
        <dl>
            <dt><?php echo $this->__('ID'); ?></dt>
            <dd><?php echo $this->__($response->id); ?></dd>

            <dt><?php echo $this->__('Status'); ?></dt>
            <dd><?php echo $this->__($response->status); ?></dd>
            <?php if (property_exists($response, 'customer')): ?>
                <dt><?php echo $this->__('Customer'); ?></dt>
                <dd><?php echo $response->customer->name . ' (' . $response->customer->email . ')'; ?></dd>
            <?php endif; ?>
            <?php
            if (property_exists($response, 'charges')):
                foreach ($response->charges as $charge):?>
                    <?php foreach ($charge as $key => $value): ?>
                        <dt>
                            <?php echo $this->__($key); ?>
                        </dt>
                        <dd>
                            <?php if ($key == 'statuses' && is_array($value)): ?>
                                <ul class="transactions">
                                    <?php foreach ($value as $status): ?>
                                        <?php if ($status): ?>
                                            <li><?php echo $this->__($status->type); ?>: <?php echo $status->inserted_at; ?></li>
                                        <?php endif;?>
                                    <?php endforeach; ?>
                                </ul>
                            <?php else: ?>
                                <?php echo $this->__($value); ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </dl>
    <?php endif; ?>
</div>
</body>
</html>