<?php
$this->setPriceDataObject($this->getSource())
?>

<?php if ((float) $this->getSource()->getPaggiInterestAmount()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('paggi')->__('Interest') ?></td>
        <td>
            <?php echo $this->displayPrices($this->getSource()->getPaggiBaseInterestAmount(), $this->getSource()->getPaggiInterestAmount()); ?>
        </td>
    </tr>
<?php endif; ?>

