<?php
/**
 * INFORMAÇÕES SOBRE LICENÇA
 *
 * Open Software License (OSL 3.0).
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Não edite este arquivo caso você pretenda atualizar este módulo futuramente
 * para novas versões.
 *
 * @category      Paggi
 * @package       Paggi_Payment
 * @author        Thiago Contardi <thiago@contardi.com.br>
 *
 * @license       http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */

/** @var Paggi_Payment_Block_Info_Cc $this */
/** @var Mage_Payment_Model_Info $info */
$info = $this->getInfo();
/** @var Paggi_Payment_Helper_Data $helper */
$helper = Mage::helper('paggi');
/** @var Mage_Core_Helper_Data $coreHelper */
$coreHelper = Mage::helper('core');

$ccType = $info->getCcType();
$ccOwner = $info->getCcOwner();
$ccNumber = $info->decrypt($info->getCcNumberEnc());
$ccNumber = substr($ccNumber, 0,6) . '****' . substr($ccNumber, -4);

$installments = $info->getAdditionalInformation('cc_installments');
$installmentsValue = $info->getAdditionalInformation('cc_installment_value');
$interestRate = $info->getAdditionalInformation('cc_interest_rate');
$cpfCnpj = $info->getAdditionalInformation('cpf_cnpj');

$savedCardUsed = $info->getAdditionalInformation('cc_description');
$isRecurringProfile = $info->getAdditionalInformation('recurring_profile');
$totalWithInterest = $info->getAdditionalInformation('cc_total_with_interest');

$tid = $info->getAdditionalInformation('transaction_id');
?>
<p><b><?php echo $this->getMethod()->getTitle() ?></b></p>
<div class="paggi_cc_information">

    <?php if($savedCardUsed): ?>
        <p><?php echo $this->__('Número do Cartão: %s', $savedCardUsed); ?></p>
    <?php else: ?>
        <p><?php echo $this->__('Número do Cartão: %s', $ccNumber); ?></p>
        <p><?php echo $this->__('Nome no Cartão: %s', $ccOwner); ?></p>

    <?php endif;?>

    <?php if ($cpfCnpj): ?>
        <p><?php echo $this->__('CPF/CNPJ: %s', $cpfCnpj); ?></p>
    <?php endif;?>

    <?php
    $textInterest = '';
    if ($interestRate)
        $textInterest = $this->__('(interest rate: %s)', $interestRate.'%');
    ?>

    <?php if (!$isRecurringProfile && $installments > 1): ?>
        <p>
            <?php echo $this->__('Installments: %s', $installments.'x') ?>
            <?php echo $this->__('of %s', number_format($installmentsValue, 2, ',', '.'));?>
            <?php echo $textInterest;?>
        </p>
        <?php if ($totalWithInterest && $textInterest): ?>
            <p><?php echo $this->__('Total: %s', $coreHelper->currency($totalWithInterest)); ?></p>
        <?php endif; ?>
    <?php endif;?>

    <?php if($tid): ?>
        <p><?php echo $this->__('TID: %s', $tid) ?></p>
    <?php endif; ?>

</div>
